version: "3.2"
services:
  gitlab:
    image: 'gitlab/gitlab-ce:9.1.0-ce.0'
    restart: always
    hostname: ${module5_host}
    environment:
      GITLAB_SIGNUP_ENABLED: 'false'
      GITLAB_OMNIBUS_CONFIG: |
        external_url "http://${module5_host}"
        # other configs
    ports:
      - '80:80'
    volumes:
      - '/srv/docker/gitlab/config:/etc/gitlab'
      - '/srv/docker/gitlab/logs:/var/log/gitlab'
      - '/srv/docker/gitlab/data:/var/opt/gitlab'
    networks:
      default:
        aliases:
          - gitlab-registry.local
  gitlab_runner:
    image: gitlab/gitlab-runner:v9.1.0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://gitlab", "||", "exit 1"]
      interval: 1m
      timeout: 10s
      retries: 5
    volumes:
      - /srv/docker/gitlab-runner:/home/gitlab-runner
      - /srv/docker/gitlab-runner-etc:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - CI_SERVER_URL=http://gitlab/ci
      - REGISTRATION_TOKEN=${GITLAB_REGISTRATION_TOKEN}
      - CI_SERVER_TOKEN=${GITLAB_CI_SERVER_TOKEN}
      - DOCKER_IMAGE="docker:latest"
      - RUNNER_NAME=dockermk
      - RUNNER_EXECUTOR=docker
      - DOCKER_PRIVILEGED=true
      - DOCKER_NETWORK_MODE=dockermk5_default
    depends_on:
      - gitlab
    restart: always
